# -*- coding: utf-8 -*-

SUBSCRIPTION_QUOTE = 'Quote'
SUBSCRIPTION_QUOTE_DEPTH = 'QuoteDepth'
SUBSCRIPTION_QUOTE_FUTURE = 'Future'
SUBSCRIPTION_QUOTE_OPTION = 'Option'
SUBSCRIPTION_TRADE_TICK = 'TradeTick'

SUBSCRIPTION_TRADE_ASSET = 'Asset'
SUBSCRIPTION_TRADE_POSITION = 'Position'
SUBSCRIPTION_TRADE_ORDER = 'OrderStatus'
SUBSCRIPTION_TRADE_TRANSACTION = 'TradeTransaction'
