# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tigeropen/push/pb/OrderStatusData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tigeropen/push/pb/OrderStatusData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'tigeropen/push/pb/OrderStatusData.proto\x12\x11tigeropen.push.pb\"\xcc\x06\n\x0fOrderStatusData\x12\n\n\x02id\x18\x01 \x01(\x12\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x04 \x01(\t\x12\x0e\n\x06strike\x18\x05 \x01(\t\x12\r\n\x05right\x18\x06 \x01(\t\x12\x12\n\nidentifier\x18\x07 \x01(\t\x12\x12\n\nmultiplier\x18\x08 \x01(\r\x12\x0e\n\x06\x61\x63tion\x18\t \x01(\t\x12\x0e\n\x06market\x18\n \x01(\t\x12\x10\n\x08\x63urrency\x18\x0b \x01(\t\x12\x0f\n\x07segType\x18\x0c \x01(\t\x12\x0f\n\x07secType\x18\r \x01(\t\x12\x11\n\torderType\x18\x0e \x01(\t\x12\x0e\n\x06isLong\x18\x0f \x01(\x08\x12\x15\n\rtotalQuantity\x18\x10 \x01(\x12\x12\x1a\n\x12totalQuantityScale\x18\x11 \x01(\x11\x12\x16\n\x0e\x66illedQuantity\x18\x12 \x01(\x12\x12\x1b\n\x13\x66illedQuantityScale\x18\x13 \x01(\x11\x12\x14\n\x0c\x61vgFillPrice\x18\x14 \x01(\x01\x12\x12\n\nlimitPrice\x18\x15 \x01(\x01\x12\x11\n\tstopPrice\x18\x16 \x01(\x01\x12\x13\n\x0brealizedPnl\x18\x17 \x01(\x01\x12\x0e\n\x06status\x18\x18 \x01(\t\x12\x15\n\rreplaceStatus\x18\x19 \x01(\t\x12\x14\n\x0c\x63\x61ncelStatus\x18\x1a \x01(\t\x12\x12\n\noutsideRth\x18\x1b \x01(\x08\x12\x11\n\tcanModify\x18\x1c \x01(\x08\x12\x11\n\tcanCancel\x18\x1d \x01(\x08\x12\x13\n\x0bliquidation\x18\x1e \x01(\x08\x12\x0c\n\x04name\x18\x1f \x01(\t\x12\x0e\n\x06source\x18  \x01(\t\x12\x10\n\x08\x65rrorMsg\x18! \x01(\t\x12\x10\n\x08\x61ttrDesc\x18\" \x01(\t\x12\x18\n\x10\x63ommissionAndFee\x18# \x01(\x02\x12\x10\n\x08openTime\x18$ \x01(\x04\x12\x11\n\ttimestamp\x18% \x01(\x04\x12\x10\n\x08userMark\x18& \x01(\t\x12\x17\n\x0ftotalCashAmount\x18\' \x01(\x01\x12\x18\n\x10\x66illedCashAmount\x18( \x01(\x01\x12\x0b\n\x03gst\x18) \x01(\x01\x12\x10\n\x08\x61ttrList\x18* \x03(\t\x12\x13\n\x0btimeInForce\x18+ \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.OrderStatusData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERSTATUSDATA']._serialized_start=63
  _globals['_ORDERSTATUSDATA']._serialized_end=907
# @@protoc_insertion_point(module_scope)
