# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tigeropen/push/pb/PushData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tigeropen/push/pb/PushData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tigeropen.push.pb import SocketCommon_pb2 as tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2
from tigeropen.push.pb import OrderStatusData_pb2 as tigeropen_dot_push_dot_pb_dot_OrderStatusData__pb2
from tigeropen.push.pb import PositionData_pb2 as tigeropen_dot_push_dot_pb_dot_PositionData__pb2
from tigeropen.push.pb import AssetData_pb2 as tigeropen_dot_push_dot_pb_dot_AssetData__pb2
from tigeropen.push.pb import QuoteData_pb2 as tigeropen_dot_push_dot_pb_dot_QuoteData__pb2
from tigeropen.push.pb import QuoteDepthData_pb2 as tigeropen_dot_push_dot_pb_dot_QuoteDepthData__pb2
from tigeropen.push.pb import TradeTickData_pb2 as tigeropen_dot_push_dot_pb_dot_TradeTickData__pb2
from tigeropen.push.pb import OrderTransactionData_pb2 as tigeropen_dot_push_dot_pb_dot_OrderTransactionData__pb2
from tigeropen.push.pb import StockTopData_pb2 as tigeropen_dot_push_dot_pb_dot_StockTopData__pb2
from tigeropen.push.pb import OptionTopData_pb2 as tigeropen_dot_push_dot_pb_dot_OptionTopData__pb2
from tigeropen.push.pb import KlineData_pb2 as tigeropen_dot_push_dot_pb_dot_KlineData__pb2
from tigeropen.push.pb import TickData_pb2 as tigeropen_dot_push_dot_pb_dot_TickData__pb2

from tigeropen.push.pb.SocketCommon_pb2 import *
from tigeropen.push.pb.OrderStatusData_pb2 import *
from tigeropen.push.pb.PositionData_pb2 import *
from tigeropen.push.pb.AssetData_pb2 import *
from tigeropen.push.pb.QuoteData_pb2 import *
from tigeropen.push.pb.QuoteDepthData_pb2 import *
from tigeropen.push.pb.TradeTickData_pb2 import *
from tigeropen.push.pb.OrderTransactionData_pb2 import *
from tigeropen.push.pb.StockTopData_pb2 import *
from tigeropen.push.pb.OptionTopData_pb2 import *
from tigeropen.push.pb.KlineData_pb2 import *
from tigeropen.push.pb.TickData_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tigeropen/push/pb/PushData.proto\x12\x11tigeropen.push.pb\x1a$tigeropen/push/pb/SocketCommon.proto\x1a\'tigeropen/push/pb/OrderStatusData.proto\x1a$tigeropen/push/pb/PositionData.proto\x1a!tigeropen/push/pb/AssetData.proto\x1a!tigeropen/push/pb/QuoteData.proto\x1a&tigeropen/push/pb/QuoteDepthData.proto\x1a%tigeropen/push/pb/TradeTickData.proto\x1a,tigeropen/push/pb/OrderTransactionData.proto\x1a$tigeropen/push/pb/StockTopData.proto\x1a%tigeropen/push/pb/OptionTopData.proto\x1a!tigeropen/push/pb/KlineData.proto\x1a tigeropen/push/pb/TickData.proto\"\xc5\x05\n\x08PushData\x12:\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32(.tigeropen.push.pb.SocketCommon.DataType\x12\x31\n\tquoteData\x18\x02 \x01(\x0b\x32\x1c.tigeropen.push.pb.QuoteDataH\x00\x12;\n\x0equoteDepthData\x18\x03 \x01(\x0b\x32!.tigeropen.push.pb.QuoteDepthDataH\x00\x12\x39\n\rtradeTickData\x18\x04 \x01(\x0b\x32 .tigeropen.push.pb.TradeTickDataH\x00\x12\x37\n\x0cpositionData\x18\x05 \x01(\x0b\x32\x1f.tigeropen.push.pb.PositionDataH\x00\x12\x31\n\tassetData\x18\x06 \x01(\x0b\x32\x1c.tigeropen.push.pb.AssetDataH\x00\x12=\n\x0forderStatusData\x18\x07 \x01(\x0b\x32\".tigeropen.push.pb.OrderStatusDataH\x00\x12G\n\x14orderTransactionData\x18\x08 \x01(\x0b\x32\'.tigeropen.push.pb.OrderTransactionDataH\x00\x12\x37\n\x0cstockTopData\x18\t \x01(\x0b\x32\x1f.tigeropen.push.pb.StockTopDataH\x00\x12\x39\n\roptionTopData\x18\n \x01(\x0b\x32 .tigeropen.push.pb.OptionTopDataH\x00\x12\x31\n\tklineData\x18\x0b \x01(\x0b\x32\x1c.tigeropen.push.pb.KlineDataH\x00\x12/\n\x08tickData\x18\x0c \x01(\x0b\x32\x1b.tigeropen.push.pb.TickDataH\x00\x42\x06\n\x04\x62odyP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08P\tP\nP\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.PushData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHDATA']._serialized_start=514
  _globals['_PUSHDATA']._serialized_end=1223
# @@protoc_insertion_point(module_scope)
