# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tigeropen/push/pb/QuoteBasicData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tigeropen/push/pb/QuoteBasicData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tigeropen.push.pb import SocketCommon_pb2 as tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2
from tigeropen.push.pb import QuoteData_pb2 as tigeropen_dot_push_dot_pb_dot_QuoteData__pb2

from tigeropen.push.pb.SocketCommon_pb2 import *
from tigeropen.push.pb.QuoteData_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&tigeropen/push/pb/QuoteBasicData.proto\x12\x11tigeropen.push.pb\x1a$tigeropen/push/pb/SocketCommon.proto\x1a!tigeropen/push/pb/QuoteData.proto\"\xdf\x06\n\x0eQuoteBasicData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x37\n\x04type\x18\x02 \x01(\x0e\x32).tigeropen.push.pb.SocketCommon.QuoteType\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x1c\n\x0fserverTimestamp\x18\x04 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08\x61vgPrice\x18\x05 \x01(\x01H\x01\x88\x01\x01\x12\x18\n\x0blatestPrice\x18\x06 \x01(\x01H\x02\x88\x01\x01\x12!\n\x14latestPriceTimestamp\x18\x07 \x01(\x04H\x03\x88\x01\x01\x12\x17\n\nlatestTime\x18\x08 \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08preClose\x18\t \x01(\x01H\x05\x88\x01\x01\x12\x13\n\x06volume\x18\n \x01(\x12H\x06\x88\x01\x01\x12\x13\n\x06\x61mount\x18\x0b \x01(\x01H\x07\x88\x01\x01\x12\x11\n\x04open\x18\x0c \x01(\x01H\x08\x88\x01\x01\x12\x11\n\x04high\x18\r \x01(\x01H\t\x88\x01\x01\x12\x10\n\x03low\x18\x0e \x01(\x01H\n\x88\x01\x01\x12\x1b\n\x0ehourTradingTag\x18\x0f \x01(\tH\x0b\x88\x01\x01\x12\x19\n\x0cmarketStatus\x18\x10 \x01(\tH\x0c\x88\x01\x01\x12\x17\n\nidentifier\x18\x17 \x01(\tH\r\x88\x01\x01\x12\x14\n\x07openInt\x18\x18 \x01(\x12H\x0e\x88\x01\x01\x12\x16\n\ttradeTime\x18\x19 \x01(\x04H\x0f\x88\x01\x01\x12\x1a\n\rpreSettlement\x18\x1a \x01(\x01H\x10\x88\x01\x01\x12\x14\n\x07minTick\x18\x1b \x01(\x02H\x11\x88\x01\x01\x12\x34\n\x02mi\x18\x1c \x01(\x0b\x32#.tigeropen.push.pb.QuoteData.MinuteH\x12\x88\x01\x01\x42\x12\n\x10_serverTimestampB\x0b\n\t_avgPriceB\x0e\n\x0c_latestPriceB\x17\n\x15_latestPriceTimestampB\r\n\x0b_latestTimeB\x0b\n\t_preCloseB\t\n\x07_volumeB\t\n\x07_amountB\x07\n\x05_openB\x07\n\x05_highB\x06\n\x04_lowB\x11\n\x0f_hourTradingTagB\x0f\n\r_marketStatusB\r\n\x0b_identifierB\n\n\x08_openIntB\x0c\n\n_tradeTimeB\x10\n\x0e_preSettlementB\n\n\x08_minTickB\x05\n\x03_miP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.QuoteBasicData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTEBASICDATA']._serialized_start=135
  _globals['_QUOTEBASICDATA']._serialized_end=998
# @@protoc_insertion_point(module_scope)
