# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tigeropen/push/pb/QuoteBBOData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tigeropen/push/pb/QuoteBBOData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tigeropen.push.pb import SocketCommon_pb2 as tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2

from tigeropen.push.pb.SocketCommon_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$tigeropen/push/pb/QuoteBBOData.proto\x12\x11tigeropen.push.pb\x1a$tigeropen/push/pb/SocketCommon.proto\"\x88\x02\n\x0cQuoteBBOData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x37\n\x04type\x18\x02 \x01(\x0e\x32).tigeropen.push.pb.SocketCommon.QuoteType\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x10\n\x08\x61skPrice\x18\x11 \x01(\x01\x12\x0f\n\x07\x61skSize\x18\x12 \x01(\x12\x12\x19\n\x0c\x61skTimestamp\x18\x13 \x01(\x04H\x00\x88\x01\x01\x12\x10\n\x08\x62idPrice\x18\x14 \x01(\x01\x12\x0f\n\x07\x62idSize\x18\x15 \x01(\x12\x12\x19\n\x0c\x62idTimestamp\x18\x16 \x01(\x04H\x01\x88\x01\x01\x42\x0f\n\r_askTimestampB\x0f\n\r_bidTimestampP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.QuoteBBOData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTEBBODATA']._serialized_start=98
  _globals['_QUOTEBBODATA']._serialized_end=362
# @@protoc_insertion_point(module_scope)
