# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tigeropen/push/pb/Request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tigeropen.push.pb import SocketCommon_pb2 as tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2

from tigeropen.push.pb.SocketCommon_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftigeropen/push/pb/Request.proto\x12\x11tigeropen.push.pb\x1a$tigeropen/push/pb/SocketCommon.proto\"\xda\x04\n\x07Request\x12\x38\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\'.tigeropen.push.pb.SocketCommon.Command\x12\n\n\x02id\x18\x02 \x01(\r\x12<\n\tsubscribe\x18\x03 \x01(\x0b\x32$.tigeropen.push.pb.Request.SubscribeH\x00\x88\x01\x01\x12\x38\n\x07\x63onnect\x18\x04 \x01(\x0b\x32\".tigeropen.push.pb.Request.ConnectH\x01\x88\x01\x01\x1a\xc8\x01\n\x07\x43onnect\x12\x0f\n\x07tigerId\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\x12\x12\n\nsdkVersion\x18\x03 \x01(\t\x12\x1a\n\racceptVersion\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0csendInterval\x18\x05 \x01(\rH\x01\x88\x01\x01\x12\x1c\n\x0freceiveInterval\x18\x06 \x01(\rH\x02\x88\x01\x01\x42\x10\n\x0e_acceptVersionB\x0f\n\r_sendIntervalB\x12\n\x10_receiveInterval\x1a\xab\x01\n\tSubscribe\x12:\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32(.tigeropen.push.pb.SocketCommon.DataType\x12\x14\n\x07symbols\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x61\x63\x63ount\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06market\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\n\n\x08_symbolsB\n\n\x08_accountB\t\n\x07_marketB\x0c\n\n_subscribeB\n\n\x08_connectP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.Request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=93
  _REQUEST._serialized_end=695
  _REQUEST_CONNECT._serialized_start=295
  _REQUEST_CONNECT._serialized_end=495
  _REQUEST_SUBSCRIBE._serialized_start=498
  _REQUEST_SUBSCRIBE._serialized_end=669
# @@protoc_insertion_point(module_scope)
