# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tigeropen/push/pb/Response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tigeropen.push.pb import SocketCommon_pb2 as tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2
from tigeropen.push.pb import PushData_pb2 as tigeropen_dot_push_dot_pb_dot_PushData__pb2
try:
  tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_SocketCommon__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.SocketCommon_pb2
try:
  tigeropen_dot_push_dot_pb_dot_OrderStatusData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_OrderStatusData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_OrderStatusData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.OrderStatusData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_PositionData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_PositionData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_PositionData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.PositionData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_AssetData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_AssetData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_AssetData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.AssetData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_QuoteData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_QuoteData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_QuoteData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.QuoteData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_QuoteDepthData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_QuoteDepthData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_QuoteDepthData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.QuoteDepthData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_TradeTickData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_TradeTickData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_TradeTickData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.TradeTickData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_OrderTransactionData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_OrderTransactionData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_OrderTransactionData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.OrderTransactionData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_StockTopData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_StockTopData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_StockTopData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.StockTopData_pb2
try:
  tigeropen_dot_push_dot_pb_dot_OptionTopData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen_dot_push_dot_pb_dot_OptionTopData__pb2
except AttributeError:
  tigeropen_dot_push_dot_pb_dot_OptionTopData__pb2 = tigeropen_dot_push_dot_pb_dot_PushData__pb2.tigeropen.push.pb.OptionTopData_pb2

from tigeropen.push.pb.SocketCommon_pb2 import *
from tigeropen.push.pb.PushData_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tigeropen/push/pb/Response.proto\x12\x11tigeropen.push.pb\x1a$tigeropen/push/pb/SocketCommon.proto\x1a tigeropen/push/pb/PushData.proto\"\xcb\x01\n\x08Response\x12\x38\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\'.tigeropen.push.pb.SocketCommon.Command\x12\x0f\n\x02id\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04\x63ode\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x10\n\x03msg\x18\x04 \x01(\tH\x02\x88\x01\x01\x12.\n\x04\x62ody\x18\x05 \x01(\x0b\x32\x1b.tigeropen.push.pb.PushDataH\x03\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_codeB\x06\n\x04_msgB\x07\n\x05_bodyP\x00P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.Response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=128
  _RESPONSE._serialized_end=331
# @@protoc_insertion_point(module_scope)
