# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tigeropen/push/pb/TickData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'tigeropen/push/pb/TickData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tigeropen/push/pb/TickData.proto\x12\x11tigeropen.push.pb\"\xdd\x01\n\x08TickData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12/\n\x05ticks\x18\x02 \x03(\x0b\x32 .tigeropen.push.pb.TickData.Tick\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x1am\n\x04Tick\x12\n\n\x02sn\x18\x01 \x01(\x03\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0e\n\x06volume\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0c\n\x04\x63ond\x18\x06 \x01(\t\x12\x10\n\x08partCode\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tigeropen.push.pb.TickData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKDATA']._serialized_start=56
  _globals['_TICKDATA']._serialized_end=277
  _globals['_TICKDATA_TICK']._serialized_start=168
  _globals['_TICKDATA_TICK']._serialized_end=277
# @@protoc_insertion_point(module_scope)
